### ISSUE TITLE
Edit deployment results in an error when replicas are edited.

### ISSUE THREAD

**Issue by mohanpindyala** [fabric8io/kubernetes-client#420]
I tried to scale deployment by editing the spec . it is throwing error 

code 
`kubernetesClient
             .extensions()
             .deployments()
             .withName(provisionRequest.name)
             .edit()
             .editSpec()
             .withReplicas(provisionRequest.replicationFactor)
             .endSpec()
             .done();`

Error 
`Failure executing: PUT at: http://localhost:8080/apis/extensions/v1beta1/namespaces/default/deployments/test2. Message: Deployment.extensions \"test2\" is invalid: spec.strategy.rollingUpdate.maxUnavailable: Invalid value: \"0\": must be an integer or percentage (e.g '5%'). Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.strategy.rollingUpdate.maxUnavailable, message=Invalid value: \"0\": must be an integer or percentage (e.g '5%'), reason=FieldValueInvalid, additionalProperties={})], group=extensions, kind=Deployment, name=test2, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=Deployment.extensions \"test2\" is invalid: spec.strategy.rollingUpdate.maxUnavailable: Invalid value: \"0\": must be an integer or percentage (e.g '5%'), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).`

Is there a way to edit deployment spec using labels instead of name ?

**Comment by jimmidyson** [comment]
This is really 2 issues.

The first issue should be fixed in next release, we were treating 0 wrongly.

> Is there a way to edit deployment spec using labels instead of name ?

This is the second issue. Not sure if edit works for lists of resources, as labels filtering returns - worth trying though :)

**Comment by mohanpindyala** [comment]
is there a workaround for editing then ? I am using 1.3.92

**Comment by jimmidyson** [comment]
There is no workaround for this I'm afraid. We will cut a new release tomorrow so not long to wait.

**Comment by mohanpindyala** [comment]
following is still not working with 1.3.94 release 
```kubernetesClient .extensions() .deployments() .withName(provisionRequest.name) .edit() .editSpec() .withReplicas(provisionRequest.replicationFactor) .endSpec() .done();```

am I missing something ?

**Comment by jimmidyson** [comment]
D'oh! I was wrongly reusing the cascading editing functionality we use for replica sets & replication controllers to ensure new pods are properly created. This obviously doesn't apply to deployments... 

#425 should fix this which we will release for you tomorrow probably. In the meantime you can work around the issue with `...cascading(false).edit()...` Sorry for the trouble!
